### ISSUE TITLE
Falling platform behavior

### ISSUE THREAD

**Issue by venividiascii** [ExOK/Celeste64#15]
If you remain standing on the highest falling platforms around the central skyscraper, the platform stops before it hits the death plane, but turns invisible, so the player falls down but remains standing on apparently thin air. And then your character can instantly warp back up to where the platform was and fall again.

**Comment by NoelFB** [comment]
Thanks! fixed in https://github.com/ExOK/Celeste64/commit/59d93e4dbd0862769c8a0ad6d5b8ff56e83b55af
