### ISSUE TITLE
"GL_INVALID_ENUM" Crash with Log file

### ISSUE THREAD

**Issue by flanderszao** [ExOK/Celeste64#17]
After getting out of the cassette level (and giving up on it) and wandering around the game crashed and I got this Log file.
Not sure how to properly create an issue, and I just wanted to report the crash.

[ErrorLog.txt](https://github.com/ExOK/Celeste64/files/14103734/ErrorLog.txt)

**Comment by NoelFB** [comment]
Thanks! This is actually two separate issues. The crash is actually due to code that handles the music beat events, which is fixed now (https://github.com/ExOK/Celeste64/commit/517991f8cdacf2c9d8fb71f53637e581399e197b). The opengl one I'll try to look into.

**Comment by NoelFB** [comment]
OK both issues should be fixed now as of https://github.com/FosterFramework/Foster/commit/6474150fcd612cf9c05383b4baf9ccc4cf6bb814 - should be working once we publish a new build.
