### ISSUE TITLE
Release the game on Steam

### ISSUE THREAD

**Issue by peterge1998** [ExOK/Celeste64#26]
I really like the idea of Celeste64!
Because I use my ChimeraOS PC at my TV for Gaming exclusively, could you please release it on Steam?

It would also make the game available for a much larger audience, like people owning a Steam Deck. 

Thx!

**Comment by NoelFB** [comment]
Thanks! Unfortunately we currently do not plan to release the game on Steam. You can add non-steam games to Steam Deck fairly easily and it looks like it's [possible on ChimeraOS](https://github.com/ChimeraOS/chimeraos/wiki/Getting-Started#non-steam-software) as well.
