### ISSUE TITLE
Fullscreen cannot be off when the screen resolution is less than or equal to 1080p

### ISSUE THREAD

**Issue by DemoJameson** [ExOK/Celeste64#31]
To be precise when I turn off fullscreen the game still fills the whole screen and I can't move or scale the game window

**Comment by NoelFB** [comment]
Hmm yeah this feels like Foster needs a way to get the monitor size so it can be scaled down to a size that actually fits. I could just make the default windowed size smaller (720p?) but then that has the same issue for smaller monitors.

**Comment by DemoJameson** [comment]
I think 720p is good enough as a temporary solution
most people have larger screen resolution than 720p

**Comment by NoelFB** [comment]
Good call, I'll do that and add an issue to Foster to solve it more long-term.

**Comment by NoelFB** [comment]
Fixed in https://github.com/ExOK/Celeste64/commit/593841acd38a76375cfd3e898f199b9c8e979684
