### ISSUE TITLE
Speedrun timing

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [ExOK/Celeste64#34]
Edit the timer in some way to make it stop in a more consistent way, being in the ending area is too loose of a requirement as you have to get to the ending area to get the final strawberry. I've edited my local version to immediately update Badeline's talk flag and to update the timer only when the talk flag is 0.

**Comment by NoelFB** [comment]
The timing does resume if you leave the area, but I agree it is awkward that it stops momentarily when going for the last Cassette. I'm potentially open to changes but I also don't want to disrupt existing speedruns, so might want get a more general consensus among runners before making changes to the timing.

**Comment by TheDrawingCoder-Gamer** [comment]
I figure that next version will be able to make a new category anyway, given how relatively major preventing auto climb onto spikes is (it's saved me multiple deaths on latest).

 In regards to timing, I set it such that time ends on talking to Badeline. Probably not the best way, but that makes the most sense to support both any% and all strawbs. Alternative I guess is to add a new item in the final area that ends the time and quits to main menu, so that you can view time.

**Comment by TheDrawingCoder-Gamer** [comment]
it seems that the consensus is that it depends on the category - the timer is stopped on last berry collected in ARB and any% it's just stopping when it currently stops. You can close this because I think the speedrunners already have it down. The most I'd suggest is an option somewhere to disable the time stop on end island for ARB

**Comment by NoelFB** [comment]
Alright! Closing for now, will consider various options as things move along.
