### ISSUE TITLE
I've created a Flatpak build for Celeste 64

### ISSUE THREAD

**Issue by brunofin** [ExOK/Celeste64#35]
Hello, I have successfully created a [Flatpak](https://flatpak.org/) build for Celeste 64.

I was wondering if this is something you'd be interesting in supporting yourselves in an official manner and publish Celeste 64 to [Flathub](https://flathub.org/). If so, I'd be happy to share with you the flatpak manifest file and the command used to build Celeste 64, and directions on how to publish it on the Flathub Linux app store.

If you're not interesting in supporting it officially yourselves, I'd be more than happy with your permission to submit and publish it to Flathub, including future updates, this will make Celeste 64 readily available in a packaging format that is supported by all major Linux distros (including the Steam Deck if I am not mistaken?) in secure sandboxed environment that is almost effortless to install and launch.

Please let me know :)

**Comment by NoelFB** [comment]
Hey! I think it's awesome to support Flatpak but I currently don't have the bandwidth to keep it up to date myself. I'm more than happy for you to publish it there. In the near future we should have a github action that builds for each platform on tagged releases so maybe long term it could be integrated with that.

**Comment by brunofin** [comment]
If you're interested, I could try to get Celeste Classic 2 (https://github.com/ExOK/Celeste2) as well, I am using this a learning experience with Flatpak and I am a big fan of Celeste, so it would be a pleasure to get involved even if by a little bit in this sense :)

**Comment by NoelFB** [comment]
Awesome! And that's fine by me, if Pico-8 games can be packed for it then I think it's cool!

**Comment by brunofin** [comment]
Hi again, sorry about this but apparently they need some manifest files to be preset in the upstream repo (here) in order for the submission to be accepted.

I took the liberty of creating a fork of the repo and adding the files there and pointing the flatpak git source to that fork for the time being, but I believe it would look better if the git source would be the original repo instead of some random fork :) the problem with that is that the manifest file needs to be updated with each new release to include the new version and release notes and since you mentioned you don't have the bandwidth to maintain the flatpak build I worry I am actually creating a problem for you, so by using the fork I could be maintaining this file instead.

Please let me know if it's ok for you if the flatpak would use a fork or if you prefer me to submit a PR to include those files here? If the files would be present here I could as well be submitting PRs in order to update the manifest files when needed and you'd have more control over it.

**Comment by NoelFB** [comment]
Hey! I'm fine with the manifest file being in a fork ... I honestly think that makes the most sense on my end. In the future I wouldn't be against an Action that perhaps automatically updates it as part of tagged releases (but that could also likely be done in the fork?).

**Comment by brunofin** [comment]
There we go, Celeste 64 is live on Flathub!

https://flathub.org/apps/com.exok.Celeste64

I am closing this issue now :)

**Comment by NoelFB** [comment]
Awesome, thank you! That's gonna be cool to have :)

**Comment by stuffed2** [comment]
Hey Brunofin, I know this is late but about celeste classic/2 it is fairly straightforward to flatpak as pico-8 games can be exported as html/js files.
