### ISSUE TITLE
Timer seems to be inaccurate

### ISSUE THREAD

**Issue by Jademalo** [ExOK/Celeste64#4]
I started playing at around 01:30. When I reached the top platform where it displays the timer, I took a screenshot and it seemed to be accurate with regards to how long I was playing showing 44:29 at 02:15.
I then collected some more strawberries and returned to the top platform at 02:31, and it showed 57:58. This still seems to be reasonably accurate as I did tab out to take the screenshot.
I then did another tape level, and at 02:50 it displayed 01:16:52, again seeming to be accurate.

After collecting all of the strawberries at 03:15, I enabled the timer in the settings menu to see how long everything took. I would have expected it to show around 01:40:00, however for some reason it showed 02:40:50.
The same time is displayed on my save file, so it's not just the ingame display.

I had tabbed out of the game for a couple of minutes at one point so I think the minutes might be accurate, but for some reason it seems like an extra hour was added to the timer.
I posted the screenshots in Discord when I took them so I can be sure of the time they were taken, and they definitely aren't correct.

![image](https://github.com/ExOK/Celeste64/assets/386846/cc0fdaf1-56c4-4b32-9528-40b00ef20834)

**Comment by NoelFB** [comment]
I think you're right! I believe the hours are rounding, instead if flooring. Looking into it!

**Comment by NoelFB** [comment]
should be fixed in https://github.com/ExOK/Celeste64/commit/0d92b5dbbd87f5d44fd29844a62eff9b694d2645

**Comment by Jademalo** [comment]
Fantastic, ty for the quick fix!

**Comment by NoelFB** [comment]
Fix is live, if it doesn't fix the issue I'll re-open this!
