### ISSUE TITLE
[Feature Request] Inverted Camera

### ISSUE THREAD

**Issue by Auride** [ExOK/Celeste64#40]
I am an inverted camera enjoyer. In other words, I like it when the camera goes the opposite direction of how it currently goes in Celeste 64. I would like to request a checkbox be added to the options which inverts the camera controls. You could add two separate boxes for invert-x and invert-y, but it wouldn't benefit me. I've also seen this implemented as an option box with the options Normal, Invert-X, Invert-Y, and Full Inverted or something like that.

Also awesome game!!! Thank you so much!!!

**Comment by NoelFB** [comment]
I'm open to that, but probably after https://github.com/ExOK/Celeste64/issues/41!

**Comment by hacktic-dev** [comment]
@NoelFB I added an inverted camera to Fuji. Shall I make a PR to merge it here?

**Comment by NoelFB** [comment]
This is done!
