### ISSUE TITLE
Make Options a Submenu

### ISSUE THREAD

**Issue by NoelFB** [ExOK/Celeste64#41]
I think game options should be in a submenu as there are going to be too many in not-too-long, similar to how 2D Celeste does it.

**Comment by hacktic-dev** [comment]
Once this is done I can move my inverted camera option there.

**Comment by Gamingjojo909** [comment]
Would indeed be beter, I'll try to do this.

**Comment by JoshuaMadd** [comment]
Would indeed be beter, I'll try to do this.
