### ISSUE TITLE
Inputs not registering correctly on Dualshock controller

### ISSUE THREAD

**Issue by supermeatboy10** [ExOK/Celeste64#53]
X button on dualshock controller seems to be acting as both a jump and a pause sometimes.  The issue seems to be related to Steam running at the same time, killing the Steam process in task manager seemed to fixed this in c64 for me. The issue didnt occur with xbox 360 controller, have seen other people mention similar things happening with non-xbox controllers though.

**Comment by NoelFB** [comment]
Yeah this is Steam Input just doing its thing, as far as I can tell. I'm not sure there's much we can do about it on our end unless there's some way to override Steam or tell it to stop.

**Comment by Kalobi** [comment]
Yeah on games that already have good controller support, Steam Input tends to make things worse. We see this with FNA Celeste a lot. If you want the controls to work while Steam is running, you'll probably have to either globally disable Steam Input in Steam settings or launch Celeste64 through Steam as a non-Steam game, which lets you disable it for that game specifically.

**Comment by NoelFB** [comment]
Yeah, that makes sense. I think I'll close this as "unable to fix" because it's not really us causing the issue and there's not much we can do on our end to fix it.
