### ISSUE TITLE
Mismatched Sound Effect Names(?)

### ISSUE THREAD

**Issue by steviegt6** [ExOK/Celeste64#6]
Constant fields' names are swapped here:
https://github.com/ExOK/Celeste64/blob/52240c15f035c66e7131161f97fa003e696aa7ee/Source/Audio/Events.cs#L22-L23

May or may not result in the incorrect sounds being used, don't know[^1].

[^1]: More specifically: I don't know whether how they're used in the source is correct anyway or not.

**Comment by NoelFB** [comment]
Huh.... yeah I think these are just wrong and need to be flipped!
