### ISSUE TITLE
Linux System Requirements incorrect

### ISSUE THREAD

**Issue by theofficialgman** [ExOK/Celeste64#79]
LIBC requirements are much higher than indicated in https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md

this is due to building some of the native libraries on ubuntu jammy. It is desirable to continue using jammy as it is the minimum version required to have proper wayland support in SDL (if you attempt to use focal to build, you will either have wayland disabled in the build or have missing symbol errors when trying to run the build on a newer distro).

the release notes should instead specify:

Linux: GLIBC 2.35+ Distros x64, ARM64, and ARM32

or something similar

**Comment by NoelFB** [comment]
Cool thanks! Updated!
